<?php

declare(strict_types=1);

namespace BitWasp\Test\Bitcoind\Config;

use BitWasp\Bitcoind\Config\FilesystemLoader;
use BitWasp\Test\Bitcoind\TestCase;
use Matomo\Ini\IniReader;

class FilesystemLoaderFixtureTest extends TestCase
{
    /**
     * @var FilesystemLoader
     */
    private $loader;

    public function setUp()
    {
        $this->loader = new FilesystemLoader(new IniReader());
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testReadFile()
    {
        $config = $this->loader->load($this->getDataFilePath("config/config1.conf"));
        $this->assertEquals([
            "rpcuser" => "username123",
            "rpcpassword" => "enterasecurepassword",
            "rpcport" => 20202,
            "rpcconnect" => "54.54.54.54",
            "regtest" => 1,
        ], $config->all());
    }
}
